service:
  apiKey: your-service-key
  # templateDirectory: ./templates

database:
  connectionUrl: postgres://qq_user:qq_passwd@127.0.0.1:5432/qq_db

notifications:
  smtp:
    from: qq-no-reply@your-organization.online
    organizerEmail: admin@your-organization.online
    host: smtp.yourserver.address
    port: 25
    username: 'your-smtp-user-name'
    password: 'your-smtp-password'
    secure: false
    tlsRejectUnauthorized: false


